name: CIFetch

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: GetPMAction
        uses: actions/checkout@v4
        with:
          repository: 4d/packageManager
          token: ${{ secrets.PAT_TOKEN }} # a personal access token to download private repo "pm"
          path: .github/packageManager
      - name: Fetch
        uses: ./.github/packageManager
        with:
          token: ${{ secrets.DLTK }} # to download tool4d, used to execute 4D code to fetch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # to fetch repository, GitHub release api
      - name: LogDownloadedFiles
        run: find ./Components # log downloaded files
