name: CIFetch

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: GetPMAction
        uses: actions/checkout@v4
        with:
          repository: 4d/packageManager
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/packageManager
      - name: Fetch
        uses: ./.github/packageManager
        with:
          token: ${{ secrets.DLTK }} # to download tool4d
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # to fetch repository, request api
      - name: LogDownloadedFiles
        run: find ./Components
