name: CIFetch

on:
  workflow_dispatch:

jobs:
  fetch:
    name: "Fetch on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest,  ubuntu-24.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: GetPMAction
        uses: actions/checkout@v4
        with:
          repository: 4d/packageManager
          token: ${{ secrets.PAT_TOKEN }} # a personal access token to download private repo "pm"
          path: .github/packageManager
          ref: testWindow
      - name: Fetch
        uses: ./.github/packageManager
        with:
          token: ${{ secrets.DLTK }} # to download tool4d, used to execute 4D code to fetch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # to fetch repository, GitHub release api
      - name: LogDownloadedFiles
        shell: bash
        run: find ./Components # log downloaded files
