name: CIFetch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: GetPMAction
        uses: actions/checkout@v4
        with:
          repository: 4d/packageManager
          token: ${{ secrets.PAT_TOKEN }}
          ref: 'action'
          path: .github/packageManager
      - name: Fetch
        uses: ./.github/packageManager
        with:
          token: ${{ secrets.DLTK }}
          project: ${{ github.workspace }}Project/SampleProjectWithDep.4DProject
      - name: Find
        run: find . ./Components
